import runloop

# Lambda functions can take in arbitrary inputs and return arbitrary outputs.
# They will automatically run in a container with all the dependencies needed.
@runloop.function
def example_agent(name: str, system_coordinator: runloop.SystemCoordinator) -> str:
    # We create a devbox that is tied to the run of this agent. It will be automatically shutdown when the agent is done.
    devbox = system_coordinator.create_devbox()

    # We can use shell tools and file tools to interact with the devbox including running arbitrary commands and writing and reading files.
    # You can use the devbox to run arbitrary code generated by your AI agent in a secure and isolated environment.
    exec_result = devbox.shell_tools.exec("echo 'executed hello from devbox'")

    return f"Devbox ID: {devbox.id}\nExec Result: {exec_result}. User: {name}"